### ISSUE TITLE
Support ccc PublicKey prefix of other fork chains

### ISSUE THREAD

**Issue by fanyinghao** [eoscanada/eos-go#130]
Other fork chain would change publickey prefix, so it's better to enable the customize the defined in https://github.com/eoscanada/eos-go/blob/master/ecc/pubkey.go#L17

**Comment by fanyang1988** [comment]
@fanyinghao the `PublicKeyPrefixCompat` is a just a tag for public key, in https://github.com/codexnetwork/codexio-go which is a fork of eos-go for codex.io, i change the `PublicKeyPrefixCompat` to a value to make it can be customize because codex.io can customize main names in chain, but i think it is not a good way, for most times, just replace the prefix compat to `EOS` is a more flexible way.

**Comment by maoueh** [comment]
Interesting. Will need to think about this, going from `const PublicKeyPrefixCompat` to `var PublicKeyPrefixCompat` so you could update the prefix are runtime.

**Comment by fanyinghao** [comment]
@maoueh Agreed. A variable definition is reasonable.

**Comment by fanyinghao** [comment]
Any update?

**Comment by maoueh** [comment]
Pushed the changes 2 days ago on `master` branch.

The master branch contains some breaking changes not yet fully documented. The changes are that we added a `context.Context` parameter to all calls that could be cancelled throughout their operation lifetime.

That is all API calls as well as some signing functions and more.

You can check this commit https://github.com/eoscanada/eosc/commit/76d29d2b4d43317bc32ab902d91334885c9a9c3e on eosc project that updated our EOSIO CLI toolkit to latest version of eos-go for how to perform the update until we release completely an updated version (in the upcoming weeks, definitely not in the upcoming 2 for now however, we have another big project we are working on).

This is resolved IMO, hence the closed issue.
