### ISSUE TITLE
Packed member in TransactionWithID struct is nil for deferred transaction

### ISSUE THREAD

**Issue by bytefly** [eoscanada/eos-go#139]
Hi, I wonder how to get a deferred tx detail in eos-go.  If I call api.GetBlockByNum the Packed member in TransactionWithID struct of response is nil but it's right for normal transactions. Do I have to call GetTransaction ?

**Comment by maoueh** [comment]
This is because the way deferred transaction are created within EOSIO software. And to complicate things further, how you create the transaction changes a bit how things get returned to you.

In both cases, you need to distinguish between the block in which the transaction was created and the block in which it was actually executed. Note that it can be the same block, but in almost all circumstances, it will be two different block.

#### Deferred push using `--delay-sec` (directly through the CLI or Wallet application)

In this case, the block in which the deferred was created, when retrieved through the standard API will be populated correctly like other transaction.

However, in the block in which the transaction was actually executed by the blockchain, the json return value looks like:

```
{
  "timestamp": "2020-02-28T15:52:24.500",
  "producer": "eosio",
  "confirmed": 0,
  "previous": "0000002df5f2cd979c24d2c75e1b24101764652dd2b2210125c35a6d73d83455",
  "transaction_mroot": "4d06783056d8b47606306686eaad21bb9a3043769510c2b8ecebbcf8f7103ec3",
  "action_mroot": "5b7ca7c109554c1ce0a4af391a298dd5dd0ea5b0db90da309d458f18990057c6",
  "schedule_version": 0,
  "new_producers": null,
  "producer_signature": "SIG_K1_Jy1kkqbgvW6o6MLSKyJSeW8YAjttBSnbLCzHHmUbYuubqXq5CVWQFrgeAy9JHmjiwBauQZrrMMfwu4ijjMXZHV5M9Bh6pB",
  "transactions": [
    {
      "status": "executed",
      "cpu_usage_us": 209,
      "net_usage_words": 0,
      "trx": "480a4adde14100097abec586d1dec805b3bfdb48c9efed5695ca02c61ea043bd"
    },
    {
     ...
```

Where a normal executed transaction in this case looks like:

```
   {
      "status": "executed",
      "cpu_usage_us": 289,
      "net_usage_words": 15,
      "trx": {
        "id": "352fd6f0e018bd8dc558dbf2fccc7cb2d73f9d1b4c7aafcb7710aef2584f3a18",
        "packed_trx": "5637595e2d00...",
        "transaction": {
          ...
        }
        ...
      }
   }
```

#### Deferred created by a smart contract

This case get's trickier. In this case, in the block that created the deferred, you will find no trace of the deferred transaction. This is because the deferred was created by a smart contract which did not generate a transaction yet. It's just recorded in the blockchain for future execution.

In the block that actually executed the transaction, you'll find it the same way as the previous case, i.e. when the transaction was pushed with a delay.

This case of the smart contract is getting more complicated. You will need to rely on an history solution to properly retrieve those transaction. Most of them have only partial support because deferred transaction are not exposed fully by the standard EOSIO `nodeos` process.

### dfuse API

The dfuse API (so basically, us :D) has full support for deferred transaction. You can get a deferred even if it's not executed yet (of course, you don't get the same level of details, since it has not executed just yet).

Check out https://docs.dfuse.io/reference/eosio/rest/fetch-transaction/ for details about our endpoint that deals with all the details of deferred transaction.
