### ISSUE TITLE
Creating transactions with optional uint64 parameter fails

### ISSUE THREAD

**Issue by fschoell** [eoscanada/eos-go#140]
I'm trying to push a pong action to [this contract](https://github.com/stableex/sx.pingpong/blob/8f7784b29f6dc3bd80a3ae4f1f75e640e78402c8/src/pingpong.sx.cpp#L28). However, creating the transactions fails as it has an optional uint64 parameter which I cannot set. 

If I use this struct: 

```go
type Pong struct {
	Account eos.Name        `json:"account"`
	Uid     eos.Uint64      `json:"uid" eos:"optional"`
	TrxId   eos.Checksum256 `json:"trx_id" eos:"optional"`
}
```

I'm getting a reflection error: 

```
panic: reflect: call of reflect.Value.IsNil on uint64 Value [recovered]
        panic: reflect: call of reflect.Value.IsNil on uint64 Value

goroutine 28 [running]:
encoding/json.(*encodeState).marshal.func1(0xc000107480)
        /usr/lib/go/src/encoding/json/encode.go:326 +0x9a
panic(0x756520, 0xc0001be3a0)
        /usr/lib/go/src/runtime/panic.go:969 +0x166
reflect.Value.IsNil(...)
        /usr/lib/go/src/reflect/value.go:1063
github.com/eoscanada/eos-go.(*Encoder).Encode(0xc000106d48, 0x785860, 0xc000146390, 0x0, 0x0)
```

If I use a pointer to avoid the call of `isNil()` on a uint64: 

```go
type Pong struct {
	Account eos.Name        `json:"account"`
	Uid     *eos.Uint64     `json:"uid" eos:"optional"`
	TrxId   eos.Checksum256 `json:"trx_id" eos:"optional"`
}
```

then creating the transaction fails with: `panic: sign transaction: get_required_keys: json: error calling MarshalJSON for type *eos.Action: Encode: unsupported type eos.Uint64`

Sending the transaction follows the example for transfering EOS. This is how I create it:

```go
func NewPong(account eos.Name, uid eos.Uint64, trxId eos.Checksum256) *eos.Action {
	return &eos.Action{
		Account: eos.AN("eosnpingpong"),
		Name:    eos.ActN("pong"),
		Authorization: []eos.PermissionLevel{
			{Actor: eos.AN("myaccount"), Permission: eos.PN("pingpong")},
		},
		ActionData: eos.NewActionData(Pong{
			Account: account,
			Uid:     uid,
			TrxId:   trxId,
		}),
	}
}
```

And this is how I push it:

```go
func (w *Worker) PushPong(account eos.Name, uid eos.Uint64, trxId eos.Checksum256) {
	tx := eos.NewTransaction([]*eos.Action{NewPong(account, uid, trxId)}, w.TxOpts)
	signedTx, packedTx, err := w.Api.SignTransaction(context.Background(), tx, w.TxOpts.ChainID, eos.CompressionNone)
	if err != nil {
		panic(fmt.Errorf("sign transaction: %s", err))
	}

	content, err := json.MarshalIndent(signedTx, "", "  ")
	if err != nil {
		panic(fmt.Errorf("json marshalling transaction: %s", err))
	}

	response, err := w.Api.PushTransaction(context.Background(), packedTx)
	if err != nil {
		panic(fmt.Errorf("push transaction: %s", err))
	}

	fmt.Printf("Transaction [%s] submitted to the network succesfully.\n", hex.EncodeToString(response.Processed.ID))
}
```

**Comment by fschoell** [comment]
Fixed it for now by adding 

```go
case *Uint64:
	return e.writeUint64(uint64(*cv))
```

To the switch statement in the encoder file ([here](https://github.com/eoscanada/eos-go/blob/7cd7a576eceb063b7ccf5ff7d9eaf62157d79547/encoder.go#L44)). Not sure if that's the recommended way of solving this, but if so it'd probably need some more pointer checks for other basic types as well.

**Comment by maoueh** [comment]
@fschoell It's a good workaround, but the encoder core should be fixed to handle those cases in fact.

Probably that both case should be fixed. Thanks for all code snippets, really good issue reporting :D 

I'll try to find time to fix both.

**Comment by maoueh** [comment]
@fschoell I fixed the bug, still some combination won't work (for example `*Int64` or `*uint64`), I'm going to improve the encoder/decoder tomorrow on those fields (mostly doing the same change done for `Uint64` type you can see on 24c0eb7).

Also for knowledge purpose, to fix the first problem you had with `eos.Uint64`, the only change required was this: https://github.com/eoscanada/eos-go/commit/24c0eb71e12533ab1888cfe7372f95c86520b826#diff-e21d668a14a336e945f446d265f089b1R237

The `IsNil` call on reflect used before was usable only for a subset of the types in Golang. `IsZero` is more encompassing and works with all type in fact.

One important note here:

```
type Pong struct {
  ID uint64 `eos:"optional"`
}
```

The binary encoding of ` Pong{ID: 0}` will be flagged as not present, because it's the empty value. This is the same behavior as with `json:"id,omitempty"`. It might or might not be a problem depending on the use case and expected value set of the field.

If it's a problem, you would be required to use `*Uint64` (because `*uint64` doesn't work yet, but will be soon).
