### ISSUE TITLE
Pack action data issue after compiling contract with the Leap CDT 3.0.1

### ISSUE THREAD

**Issue by sebastianmontero** [eoscanada/eos-go#189]
After compiling a contract with the LEAP CDT, I can no longer call contract actions using the eos go client I get a pack data exception, like the following:

```
cannot pack action data for action: Internal Service Error: Pack data exception: Missing field 'first' in input object while processing struct
```
I'm using eos-go v0.10.2. 

Why is this?

**Comment by maoueh** [comment]
No idea, if you can create a reproducible test case in `eos-go`, I can take a look. You will need the ABI as well as the struct data you are trying to encode. It's possible the format has changed.

Try with `develop` branch, some changes landed there around improved support for LEAP.

**Comment by matthewdarwin** [comment]
From telegram:

Sebastian Montero, [2022-10-29 7:51 P.M.]
Hi, I'm not sure if this is the correct forum for this question, but after compiling a contract with the LEAP CDT, I can no longer call contract actions using the eos canada eos go client(v0.10.2), I get a pack data exception, like the following:
cannot pack action data for action: Internal Service Error: Pack data exception: Missing field 'first' in input object while processing struct

Is anyone having the same issue?

Jeeyong "conr2d" Um, [2022-10-29 11:43 P.M.]
[In reply to Sebastian Montero]
I guess this change causes your issue.
https://github.com/AntelopeIO/cdt/commit/e8bc58187bc7a0c7329f6e4029bd71cb14eeb829

Jeeyong "conr2d" Um, [2022-10-29 11:45 P.M.]
If you provide the items with the key "key" and "value", it should be "first" and "second" instead. Or, eos go client might have hard coded key names, then it needs to be fixed by the maintainer of eos go client.

**Comment by sebastianmontero** [comment]
I tried with the develop branch, but I still get the same error

**Comment by maoueh** [comment]
I searched for `key` within the repository and did not spot the offending occurence, a repro test case will be needed.

**Comment by sebastianmontero** [comment]
@maoueh my bad, the "key" and "value" names are specified in the field struct tags, changing them fixed the issue
